# -*- coding: utf-8 -*-
"""Google_image_crawling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQrF5w-5Lr3wF0BsK-hc4hpHZbKWzcI-
"""

!pip install icrawler

from icrawler.builtin import BaiduImageCrawler, BingImageCrawler, GoogleImageCrawler

google_crawler = GoogleImageCrawler(
    feeder_threads=1,
    parser_threads=1,
    downloader_threads=4,
    storage={'root_dir': 'prac'})
filters = dict(
    size='large',
    color='black',
    license='commercial,modify',
    date=((2017, 1, 1), (2017, 11, 30)))
google_crawler.crawl(keyword='cat', filters=filters, offset=0, max_num=100,
                     min_size=(200,200), max_size=None, file_idx_offset=0)

from icrawler.builtin import BaiduImageCrawler, BingImageCrawler, GoogleImageCrawler

google_crawler = GoogleImageCrawler(
    feeder_threads=1,
    parser_threads=1,
    downloader_threads=4,
    storage={'root_dir': 'dog_sit'})
filters = dict(
    size='large',
    color='black',
    license='commercial,modify',
    date=((2017, 1, 1), (2017, 11, 30)))
google_crawler.crawl(keyword='dog sit', filters=filters, offset=0, max_num=100,
                     min_size=(200,200), max_size=None, file_idx_offset=0)

/content/drive/My Drive